from typing import Any

from _mappers.mapper import EntityDef
from _mappers.mapper import EntityFactory
from _mappers.mapper import Fields

def is_attrs(entity: Any) -> bool: ...
def get_fields(entity: EntityDef) -> Fields: ...
def get_factory(fields: Fields, entity: EntityDef) -> EntityFactory: ...
