from typing import Any

from _mappers.entities import _EntityClass
from _mappers.entities import _EntityFactory
from _mappers.entities import _Fields

def is_dataclass(entity: Any) -> bool: ...
def get_fields(entity: _EntityClass) -> _Fields: ...
def get_factory(fields: _Fields, entity: _EntityClass) -> _EntityFactory: ...
